environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      BITS: "64"
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
build_script:
  - cargo build --verbose --all --release
test_script:
  - cargo test --verbose --all --release
artifacts:
  - path: target/release/azi.exe
