[package]
name = "azi"
version = "0.1.0"
authors = ["Pascal"]
edition = "2018"

[[bin]]
name = "azi"
path = "src/main.rs"

[dependencies]
clap = "2.33"
dirs = "1.0"
env_logger = "0.6"
log = "0.4"
regex = "1.1"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
